safe:       true
port:       4000
markdown:   kramdown

kramdown:
  auto_ids: false
  syntax_highlighter_opts:
      disable: true

exclude:
  - Gemfile
  - Rakefile
  - orgeln-herrenberg/Rakefile
  - README.md
